version: '3'
services:
  playground-web-db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: playground-web
    ports:
      - 27017:27017
  playground-web-frontend:
    image: playground-web-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://playground-web-backend:8000/
    ports:
      - 3000:3000
  playground-web-backend:
    image: playground-web-backend:latest
    environment:
      MONGODB_URI: mongodb+srv://123:123@cluster0.9ddrq4e.mongodb.net/?retryWrites=true&w=majority
    ports:
      - 8000:8000